import pandas as pd
import json
import os
import re
import tkinter as tk
from tkinter import filedialog

def get_json(formula):
    result = {}
    if formula:
        match = re.search(r'\[(.+?)\]', formula)
        if match:
            result['tagId'] = match.group(1)
        else:
            result['formula'] = formula
    return json.dumps(result)

def process_excel(input_file):
    df = pd.read_excel(input_file, sheet_name='IN', header=1)

    output_df = pd.DataFrame(columns=[
        'Id', 'Delete', 'Type', 'Path', 'Description', 'Code', 'Prototype',
        'PropertyPath', 'UomPath', 'ValueType', 'DataType', 'DataReference',
        'Configuration', 'ConfigurationAutoGenerated', 'SecurityAttributeValue',
        'HierarchyScopePaths', 'PropertyType', 'ClassPath', 'DescriptionOverridden'
    ])

    for index, row in df.iterrows():
        source = row['Источник данных']
        if pd.notna(row.get('Дубли по тегам', pd.NA)):
            continue

        new_row = {
            'Id': '',
            'Delete': 'false',
            'Type': 'PropertyConfiguration',
            'Path': row['Путь объекта в ОМ оборудования'],
            'Description': '',
            'Code': '',
            'Prototype': '',
            'PropertyPath': '/Root/PropertyTemplates/AnalogInput',
            'UomPath': '/Root/Units/NoUnits',
            'ValueType': 'Float64',
            'DataType': 'Float',
            'DataReference': '',
            'ConfigurationAutoGenerated': 'true',
            'SecurityAttributeValue': '',
            'HierarchyScopePaths': '',
            'PropertyType': 'Regular',
            'ClassPath': '/Root/Classes/Property',
            'DescriptionOverridden': 'false'
        }

        if source == 'Формула':
            formula = row['Формула расчёта, ссылка на источник'] if pd.notna(row['Формула расчёта, ссылка на источник']) else ''
            new_row['Configuration'] = get_json(formula)
        elif source == 'тег БДВР':
            tag_value = row['Имя тега']
            if pd.notna(tag_value):
                new_row['Configuration'] = json.dumps({'tagId': str(tag_value)})
            else:
                print(f"Предупреждение: Пустое значение тега в строке {index}")
                continue

        output_df = pd.concat([output_df, pd.DataFrame([new_row])], ignore_index=True)

    output_file = os.path.join(os.path.dirname(input_file), 'VBAcorrect.xlsx')
    with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
        output_df.to_excel(writer, sheet_name='Models', index=False)

    print(f"Обработка завершена. Результаты сохранены в файл: {output_file}")

if __name__ == "__main__":
    root = tk.Tk()
    root.withdraw()
    initial_dir = r"C:\Users\Professional\Documents\GitHub\jaus_repository\VBA-freelance"
    input_file = filedialog.askopenfilename(
        filetypes=[("Excel files", "*.xlsx;*.xls;*.xlsm")],
        initialdir=initial_dir
    )
    if input_file:
        process_excel(input_file)
    else:
        print("Файл не выбран. Программа завершена.")